name: ShadowUtils
version: '${version}'
main: me.quickscythe.shadowcore.Main
api-version: '1.21'
dependencies:
  server:
    SimpleVoiceChat:
      load: BEFORE
      required: false
      join-classpath: true